name: dev cicd pipeline

on:
  workflow_dispatch:
    inputs:
      destination:
        required: false
        type: choice
        description: Where to deploy
        default: 'stage'
        options:
          - stage
          - prod
  env:
    DEV_AUTO_RUN: 'false'

  push:
    branches: [ "dev" ]
  env: 
    DEV_AUTO_RUN: 'true'

jobs:
  build_back:
    runs-on: ubuntu-22.04
    steps:

    - name: checkout
      uses: actions/checkout@v3

    - name: env mapping prod
      if: ${{ (github.event.inputs.destination == 'prod' || env.DEV_AUTO_RUN == 'true') }}
      run: |
        echo "${{ env.DEVAUTORUN }}"
        echo "${{ github.event.inputs.destination }}"

    - name: show env
      run: |
        echo "$DEV_AUTO_RUN"
        echo "${{ github.event.inputs.destination }}"
        echo $DEV_AUTO_RUN
        echo ${{ env.DEV_AUTO_RUN }}

