name: dev cicd pipeline

on:
  workflow_dispatch:
    inputs:
      destination:
        required: false
        type: choice
        description: Where to deploy
        default: 'stage'
        options:
          - stage
          - prod

  push:
    branches: [ "dev" ]

env: 
  DEV_AUTO_RUN: 'true'

jobs:
  build_back:
    runs-on: ubuntu-22.04
    steps:

    - name: checkout
      uses: actions/checkout@v3

    - name: env mapping prod
      if: ${{ (github.event.inputs.destination == 'prod' || (github.head_ref || github.ref_name) == 'dev' ) }}
      run: |
        echo "${{ env.DEV_AUTO_RUN }}"
        echo ${{ github.head_ref }} ${{ github.ref_name }}
        echo "${{ github.event.inputs.destination }}"
        echo destination prod or github.head_ref github.ref_name dev

    - name: show env
      run: |
        echo "$DEV_AUTO_RUN"
        echo "${{ github.event.inputs.destination }}"
        echo $DEV_AUTO_RUN
        echo ${{ env.DEV_AUTO_RUN }}
        echo ${{ github.head_ref }} ${{ github.ref_name }} 
        echo ${{ (github.head_ref || github.ref_name) }}

